import type { Metadata } from "next";

import { CopilotKit } from "@copilotkit/react-core";
import "./globals.css";
import "@copilotkit/react-ui/v2/styles.css";
import { ThemeProvider } from "@/hooks/use-theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <ThemeProvider>
          <CopilotKit runtimeUrl="/api/copilotkit" agent="my_agent">
            {children}
          </CopilotKit>
        </ThemeProvider>

      </body>
    </html>
  );
}
