import type { Metadata } from "next";

import "./globals.css";
import "@copilotkit/react-ui/v2/styles.css";
import { ThemeProvider } from "@/hooks/use-theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
